// <auto-generated />
using System;
using GameServerLauncher.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameServerLauncher.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameServerLauncher.Models.ServerStatistic", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<float>("Bandwidth")
                        .HasColumnType("real");

                    b.Property<float>("CPU")
                        .HasColumnType("real");

                    b.Property<float>("RAMAmount")
                        .HasColumnType("real");

                    b.Property<float>("RAMUsage")
                        .HasColumnType("real");

                    b.Property<float>("StorageAmount")
                        .HasColumnType("real");

                    b.Property<float>("StorageUsage")
                        .HasColumnType("real");

                    b.HasKey("Time");

                    b.ToTable("ServerStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
